### ISSUE TITLE
Missing set.py 

### ISSUE THREAD

**Issue by kennyjudo** [TheCellule/blesonwin#3]
its seems missing setup.py or others file, i try pip install and its return an error

**Comment by WayneKeenan** [comment]
The setup.py is here: https://github.com/TheCellule/python-blesonwin/blob/master/blesonwin/setup.py

However, there are pre-rolled binary versions already built in PyPi, have you looked at the Bleson installation instructions (and notes!): https://bleson.readthedocs.io/en/latest/installing.html
