### ISSUE TITLE
python setup.py build   fail

### ISSUE THREAD

**Issue by EggplantPotatoes** [TheCellule/blesonwin#7]
C:\Users\Administrator\Desktop\python-blesonwin-master\python-blesonwin-master\blesonwin>python setup.py build
Version=0.0.dev1
running build
running build_ext
building 'blesonwin' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Users\Administrator\AppData\Local\Programs\Python\Python38\include -ID:\Users\Administrator\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpblesonwin.cpp /Fobuild\temp.win-amd64-3.8\Release\blesonwin.obj /std:c++latest
blesonwin.cpp
c:\users\administrator\desktop\python-blesonwin-master\python-blesonwin-master\blesonwin\winrt/base.h(9) : warning: Visual Studio 2017 version 15.3 or later is recommended.
c:\users\administrator\desktop\python-blesonwin-master\python-blesonwin-master\blesonwin\winrt/base.h(44): fatal error C1083: Cannot open include file: 'optional': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

From Windows 10 x64  with Python 3.8:

**Comment by WayneKeenan** [comment]
I've just checked in the branch called 64bit_latest_tools which successfully compiles when using the release.cmd script to build.

The Python test script in this repo works also.

However, as an aside, kinda, I've just noticed the main bleson module has an import issue with signal that needs looking at. 

But I hope this help, please let me know.

**Comment by WayneKeenan** [comment]
This should now be fixed, please see: https://github.com/TheCellule/python-bleson/issues/79
